import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import Providers from "./Providers";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";
import Loading from "./Components/Loading";

const geistSans = Geist({ subsets: ["latin"], display: "swap", variable: "--font-geist-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], display: "swap", variable: "--font-geist-mono" });

export const metadata = {
  title: "EventGuide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`antialiased ${geistSans.className} ${geistMono.className}`}
      >
        <Toaster position="top-right" />
        <Providers>

          <Navbar></Navbar>
          <Suspense fallback={<Loading></Loading>}>
            {children}
          </Suspense>
          <Footer></Footer>

        </Providers>

      </body>
    </html>
  );
}
